### ISSUE TITLE
never resolves with through streams 2.1.2 and 2.1.3

### ISSUE THREAD

**Issue by transitive-bullshit** [epeli/node-promisepipe#16]
The following example worked fine with `2.1.1`:

```js
const fs = require('fs')
const pipe = require('promisepipe')
const through2 = require('through2')

const src = fs.createReadStream('package.json')
const dest = through2()

pipe(src, dest)
  .then(() => {
    console.log('done')
  }, (err) => {
    console.error(err)
  })
```

With `2.1.2` and `2.1.3`, the pipe never resolves the promise as it doesn't wait on the through stream's `finish` event.

**Comment by transitive-bullshit** [comment]
@epeli it seems like it'd be innocuous to just always wait on `allEvents` for both readable and writeable streams, but I may be missing something?

Trying to determine the type of stream and only waiting on a subset of events seems brittle.

**Comment by MartinKolarik** [comment]
See #2. Waiting for all events creates a problem with Duplex streams.

**Comment by MartinKolarik** [comment]
Actually, I'm not sure why you'd expect the promise to resolve in this case. Unless I'm missing something, `dest` is a readable stream (well, duplex stream), which isn't piped anywhere, so it never finishes?

**Comment by transitive-bullshit** [comment]
Is there any viable solution for this, then? Specifically, [@google-cloud/storage](https://github.com/googleapis/nodejs-storage) is using a through stream and this breaks my use case with them.

**Comment by MartinKolarik** [comment]
What's the point of having a through stream at the end if its output is ignored? The solution would be piping the stream somewhere so that the output is actually used.

**Comment by transitive-bullshit** [comment]
It's common practice to have composable APIs return through streams instead of write streams. I'm not saying this is right, but Google at least does this quite a bit in their libs ([example](https://github.com/googleapis/nodejs-storage/blob/master/src/file.js#L483)).

**Comment by transitive-bullshit** [comment]
Sorry, wrong link.

**Comment by transitive-bullshit** [comment]
> Actually, I'm not sure why you'd expect the promise to resolve in this case. Unless I'm missing something, dest is a readable stream (well, duplex stream), which isn't piped anywhere, so it never finishes?
Its `finish` event is called.

**Comment by transitive-bullshit** [comment]
It's entirely possible that I'm misunderstanding streams here, so thank you for your patience :)

I'm just trying to find a minimal repro example of something which I was really surprised doesn't work ala awaiting a google cloud storage upload via File.createWriteStream.

**Comment by MartinKolarik** [comment]
Could you share a small example of the actual code using the Google library + promisepipe? I'm not familiar with this "return through streams instead of write streams" practice and I'm trying to understand how exactly it works.

Is it something like, "it's a write stream which writes the data where you want, but you can also read from it, if you want to use the same data for something else at the same time"? If that's the case, I think just adding something like https://www.npmjs.com/package/dev-null at the of the stream chain should work.

**Comment by transitive-bullshit** [comment]
Adding `dev-null` works perfectly -- thanks!

[This](https://github.com/transitive-bullshit/abstract-object-storage/blob/master/lib/methods/upload-stream.js) is the use case I'm using promisepipe for. It's part of a wrapper library around google cloud storage.

**Comment by transitive-bullshit** [comment]
The `uploadStream` from that example would be called like this:

```js
const storage = require('abstract-object-storage').defaults({
  bucket: 'my-test-bucket'
})

await storage.uploadStream({
  key: 'test/example.jpg',
  stream: fs.createReadStream('./example.jpg')
})

const buffer = await storage.downloadBuffer({
  key: 'test/example.jpg'
})

**Comment by MartinKolarik** [comment]
👍 great, this is how I expected it to work and adding `/dev/null` is really the right solution in this case. I'll update the readme later to clarify this.

**Comment by transitive-bullshit** [comment]
Thanks a ton @MartinKolarik -- you've been super helpful!

**Comment by transitive-bullshit** [comment]
Adding `dev-null` works with the `through2` package, but it still fails to resolve with `duplexify`, which is what my primary use case for google cloud storage uses.

The following example never resolves:

```js
const fs = require('fs')
const pipe = require('promisepipe')
const duplexify = require('duplexify')
const devnull = require('dev-null')

const src = fs.createReadStream('package.json')
const dest = duplexify()

pipe(src, dest, devnull())
  .then(() => {
    console.log('done')
  }, (err) => {
    console.error(err)
  })
```

**Comment by MartinKolarik** [comment]
I was just thinking today that adding `/dev/null` might be unnecessary. Since the output of the last stream isn't piped anywhere (as is the case for all other streams except the last one), the problem from #2 doesn't really apply here and so I think this should work:
 - for the first n - 1 streams, use the current detection method and listen only to some events (based on whether the stream is readable or writable or duplex)
 - for the last stream, listen to all events

@jballant, @marcelboettcher you guys were reporting issue #2, do you remember if you had a duplex stream as last stream in the chain, or if it was in the middle? Also, can you check if my suggestion makes sense?

Now that I think about it, can we actually get into a situation where any of the streams except the last one is not readable (or duplex, which is readable too)? I would say the answer is no, and in that case, we could remove the detection completely and just listen to writable events on the last stream, and readable events on all previous streams.

**Comment by MartinKolarik** [comment]
@transitive-bullshit I don't think you're using `duplixify` correctly. You are supposed to give it two existing streams. Your example doesn't work even when promisepipe listens to all events, as the `duplexify` stream doesn't fire any events in this case.

**Comment by transitive-bullshit** [comment]
Everything regarding listening to certain events seems very brittle to me and I'm sure is better abstracted elsewhere. I'm going to experiment with rewriting the internals via [pump](https://github.com/mafintosh/pump) which ala [pump-promise](https://github.com/basicsharp/pump-promise).

**Comment by MartinKolarik** [comment]
Please reopen if this is still a problem.

**Comment by peecky** [comment]
Hello.

I got a problem when I use this module with the Google cloud storage. I try to store data to the storage, but the code never ends. The writable file stream of the Google cloud storage has `readable` and `_read` properties, thus the `finish` event is ignored.

Here is my environments and test cases.

node.js: v8.12.0
promisepipe: v3.0.0
@google-cloud/storage: v2.4.3

sample code:
```javascript
const promisePipe = require('promisepipe');
const { Storage } = require('@google-cloud/storage');

(async () => {
    const storage = new Storage({
        projectId: 'myProjectId',
        keyFilename: 'myKeyFilePath'
    });
    const bucket = storage.bucket('myBucket');
    const file = bucket.file('data.csv');
    await promisePipe(fs.createReadStream('./src.csv'), file.createWriteStream());
    console.log('done');
})();
```

the diff of node_modules/promisepipe/index.js for debugging:
```diff
@@ -29,6 +29,10 @@
       const fn = evt === 'error' ?
         err => reject(new StreamError(err, stream)) :
         () => {
+          console.log('event', evt);
+          console.log('stream index', state.streams.indexOf(stream));
+          console.log('isReadable', stream.readable, typeof stream._read === 'function');
+          console.log('\n');
           // For readable streams, we ignore the "finish" event. However, if there
           // already was an error on another stream, the "end" event may never come,
           // so in that case we accept "finish" too.
@@ -65,6 +69,7 @@
 
 function allStreamsDone(allStreams) {
   let state = {};
+  state.streams = allStreams;
   let firstRejection;
 
   return Promise.all(allStreams.map(stream => streamPromise(stream, state).catch((e) => {
```

output:
```
event end
stream index 0
isReadable false true


event close
stream index 0
isReadable false true


event finish
stream index 1
isReadable true true
```
The `done` message is not printed.

Also, I tried the `dev-null`, but got another problem
```javascript
await promisePipe(fs.createReadStream('./src.csv'), file.createWriteStream(), require('dev-null')());
```

output:
```
event end
stream index 0
isReadable false true


event close
stream index 0
isReadable false true


event close
stream index 1
isReadable true true


event finish
stream index 2
isReadable undefined false


{ Error: The uploaded data did not match the data from the server. As a precaution, the file has been deleted. To be sure the content is the same, you should try uploading the file again.
    at Pumpify.evt.error.err (./node_modules/promisepipe/index.js:30:23)
    at emitOne (events.js:121:20)
    at Pumpify.emit (events.js:211:7)
    at Pumpify.Duplexify._destroy (./node_modules/duplexify/index.js:191:15)
    at ./node_modules/duplexify/index.js:182:10
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
  source: 
   Pumpify {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: false,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: true,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     domain: null,
     _events: 
      { end: [Array],
        prefinish: [Function],
        writing: [Function],
        error: [Function],
        finish: [Function],
        uncork: [Object] },
     _eventsCount: 6,
     _maxListeners: undefined,
     _writableState: 
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: true,
        ended: true,
        finished: false,
        destroyed: true,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 1,
        writing: true,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: [Function: nop],
        writelen: 1,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 1,
        prefinished: true,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: false,
     allowHalfOpen: true,
     _writable: 
      DestroyableTransform {
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: true,
        _transformState: [Object],
        _destroyed: false,
        _transform: [Function: noop] },
     _readable: 
      Duplexify {
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: true,
        _writable: [Object],
        _readable: null,
        _readable2: null,
        _autoDestroy: true,
        _forwardDestroy: true,
        _forwardEnd: true,
        _corked: 0,
        _ondrain: null,
        _drained: true,
        _forwarding: false,
        _unwrite: [Function: clear],
        _unread: null,
        _ended: true },
     _readable2: 
      Duplexify {
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: true,
        _writable: [Object],
        _readable: null,
        _readable2: null,
        _autoDestroy: true,
        _forwardDestroy: true,
        _forwardEnd: true,
        _corked: 0,
        _ondrain: null,
        _drained: true,
        _forwarding: false,
        _unwrite: [Function: clear],
        _unread: null,
        _ended: true },
     _autoDestroy: true,
     _forwardDestroy: false,
     _forwardEnd: true,
     _corked: 1,
     _ondrain: null,
     _drained: true,
     _forwarding: false,
     _unwrite: [Function: clear],
     _unread: [Function: clear],
     _ended: true,
     _read: [Function: bound ],
     _write: [Function] },
  originalError: { Error: The uploaded data did not match the data from the server. As a precaution, the file has been deleted. To be sure the content is the same, you should try uploading the file again.
    at delete (./node_modules/@google-cloud/storage/build/src/file.js:1303:35)
    at Util.handleResp (./node_modules/@google-cloud/common/build/src/util.js:141:9)
    at retryRequest (./node_modules/@google-cloud/common/build/src/util.js:422:22)
    at onResponse (./node_modules/retry-request/index.js:200:7)
    at ./node_modules/teeny-request/build/src/index.js:208:17
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7) code: 'FILE_NO_UPLOAD', errors: [ null ] } }
```

Anyway, this code works well
```javascript
await new Promise((resolve) => {
    fs.createReadStream('./src.csv').pipe(file.createWriteStream())
    .on('finish', () => resolve());
});
```
