### ISSUE TITLE
Add 'use strict' to module

### ISSUE THREAD

**Issue by daecabhir** [epeli/node-promisepipe#6]
We're currently running under Node.js 4.x, and attempting to use promisepipe results in the following error:

SyntaxError : Block-scoped declarations (let, const, function, class) not yet supported outside strict mode.

**Comment by epeli** [comment]
Too much ES6 syntax for node 4 :(  https://travis-ci.org/epeli/node-promisepipe/jobs/213022236

**Comment by zamnuts** [comment]
@epeli there are only 2 instances of syntax in use that are not compatible with node 4: destructuring and the rest operator. I'd like to use this helpful module in my (still) node 4 project. The fixes (in conjunction with the addition of `'use strict';`) are trivial:

To replace `const { message = err } = err || {};` in [b2287d05b6 index.js:6](https://github.com/epeli/node-promisepipe/blob/b2287d05b69d1e41da169fdff43057d03b06b1c0/index.js#L5):
```javascript
const message = err && err.message || err;
```

To replace `function promisePipe(...streams) {` in [b2287d05b6 index.js:31](https://github.com/epeli/node-promisepipe/blob/b2287d05b69d1e41da169fdff43057d03b06b1c0/index.js#L5):
```javascript
/**
 * @param {...Stream} stream
 */
function promisePipe(stream) {
  let i = arguments.length;
  const streams = [];
  while ( i-- ) streams[i] = arguments[i];
  // ...
```

I would be happy to provide a PR.

**Comment by epeli** [comment]
pr welcome

**Comment by zamnuts** [comment]
Sorry for the additional commit dupes, screwed up the commit meta and had to amend + force push. Hopefully they get cleaned up via GC at some point...

Anyways, PR ready.
